import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'vi' | 'km';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const translations: any = {
  vi: {
    // Common
    leaderboard: 'Bảng xếp hạng',
    weekly: 'Hàng tuần',
    all_time: 'Tất cả',
    settings: 'Cài đặt ứng dụng',
    language: 'Ngôn ngữ',
    vietnamese: 'Tiếng Việt',
    khmer: 'Tiếng Khmer',
    back: 'Quay lại',
    confirm: 'Xác nhận',
    close: 'Đóng',
    save: 'Lưu',
    cancel: 'Huỷ',
    continue: 'Tiếp tục chơi',
    exit: 'Thoát',
    login: 'Đăng nhập tài khoản',
    login_user: 'Đăng nhập',

    // Settings Screen
    notif_settings: 'Thông báo',
    study_reminder: 'Nhắc học bài mỗi ngày',
    reminder_time: 'Thời gian nhắc',
    app_info: 'Thông tin ứng dụng',
    intro: 'Giới thiệu',
    version: 'Phiên bản',
    assistant_settings: 'Trợ lý AI',
    show_chat_button: 'Hiển thị nút Chat',
    // Support Screen
    support_feedback: 'Hỗ trợ và Phản hồi',
    feedback_type: 'Loại phản hồi',
    suggestion: 'Góp ý',
    report_issue: 'Báo lỗi',
    subject: 'Tiêu đề',
    detail: 'Nội dung chi tiết',
    send_feedback: 'Gửi phản hồi',
    login_to_send: 'Đăng nhập để gửi phản hồi',
    // Profile Screen
    my_profile: 'Hồ sơ của tôi',
    edit_profile: 'Chỉnh sửa hồ sơ',
    favorites: 'Nội dung yêu thích',
    achievements: 'Thành tích của tôi',
    logout: 'Đăng xuất',
    logout_full: 'Đăng xuất tài khoản',
    points: 'Điểm',
    rank: 'Top',
    guest: 'Khách',
    login_to_view: 'Đăng nhập để xem thông tin',
    login_to_use: 'Đăng nhập để sử dụng tính năng này',
    logout_confirm_msg: 'Bạn có chắc chắn muốn đăng xuất',
    login_required: 'Yêu cầu đăng nhập',

    // Quiz Screen
    quiz_title: 'Thử thách',
    question: 'Câu',
    start_quiz: 'Bắt đầu',
    daily_challenge: 'Thử thách hằng ngày',
    correct: 'Chính xác',
    wrong_answer: 'Sai rồi',
    quiz_desc: 'Vượt qua các câu hỏi để tích lũy thêm điểm',
    total_score: 'Tổng điểm',
    current_rank: 'Hạng hiện tại',
    categories: 'Chủ đề thử thách',
    questions: 'Bộ câu hỏi',
    performance: 'Thành tích',
    view_all: 'Xem tất cả...',
    completed: 'Hoàn thành',
    recent_performance: 'Dựa trên các bài thi gần đây',
    choose_topic: 'Hôm nay bạn muốn thử thách về chủ đề gì nào',
    pagoda_quiz: 'Ngôi chùa Khmer',
    culture_quiz: 'Văn hóa Khmer',
    food_quiz: 'Ẩm thực Khmer',
    vocab_quiz: 'Học tiếng Khmer',
    vocab_quiz_subtitle: 'Ghép tiếng Khmer - tiếng Việt',
    vocab_challenge_questions: 'câu hỏi thử thách từ vựng',
    correct_answer_points_msg: 'Cộng 5 điểm cho mỗi câu đúng',
    login_required_long_msg: 'Bạn cần đăng nhập để tham gia thử thách và tích luỵ điểm xếp hạng',
    exit_game_title: 'Thoát khỏi trò chơi',
    exit_game_msg: 'Tiến trình hiện tại của bạn sẽ\nkhông được lưu lại',
    replay: 'Chơi lại',
    choose_another_quiz: 'Chọn bộ câu hỏi khác',
    answered_correctly: 'Trả lời đúng',
    questions_count: 'câu',
    points_earned: 'Điểm vừa tích luỹ',
    saving_results: 'Đang lưu thành tích...',
    results_saved: 'Đã lưu thành tích',
    excellent: '🎉 Xuất sắc',
    well_done: '👏 Tốt lắm',
    keep_it_up: '💪 Cố lên',

    // Matching Game
    matching_challenge: 'Ghép từ vựng',
    matching_challenge_title: 'Thử thách Ghép từ',
    matching_challenge_desc: 'Hãy ghép các cặp từ Khmer và nghĩa tiếng Việt tương ứng thật nhanh nhé!',
    start_matching: 'Bắt đầu ghép từ',

    // Personal Info
    personal_info: 'Thông tin cá nhân',
    full_name: 'Họ và tên',
    email: 'Email',
    change_password: 'Đổi mật khẩu',
    current_password: 'Mật khẩu hiện tại',
    new_password: 'Mật khẩu mới',
    confirm_new_password: 'Xác nhận mật khẩu mới',
    save_changes: 'Lưu thay đổi',
    error: 'Lỗi',
    name_required: 'Họ và tên không được để trống',
    unsaved_changes: 'Thay đổi chưa lưu',
    exit_confirm_msg: 'Bạn có chắc chắn muốn thoát? Các thay đổi của bạn sẽ bị mất.',
    stay: 'Ở lại',
    not_logged_in: 'Chưa đăng nhập',
    pass_fields_required: 'Vui lòng điền đầy đủ các trường để đổi mật khẩu',
    pass_mismatch: 'Mật khẩu mới không khớp',
    pass_too_short: 'Mật khẩu mới tối thiểu 6 ký tự',
    user_not_found: 'Không tìm thấy tài khoản',
    wrong_old_pass: 'Mật khẩu hiện tại không chính xác',
    update_success: 'Cập nhật thành công',
    update_failed: 'Cập nhật thất bại',

    // Support Screen Extra
    faq: 'Câu hỏi thường gặp',
    feedback_section: 'Gửi phản hồi cho chúng tôi',
    feedback_placeholder: 'Nhập nội dung phản hồi...',
    subject_placeholder: 'Nhập tiêu đề phản hồi...',
    subject_required: 'Vui lòng nhập tiêu đề và nội dung',
    content_required: 'Vui lòng nhập nội dung phản hồi',
    feedback_success: 'Đã gửi phản hồi thành công',
    feedback_failed: 'Gửi phản hồi thất bại',
    tap_to_see_guide: 'Bấm để xem hướng dẫn chi tiết',
    // FAQ Extra
    faq_how_to_use: 'Cách sử dụng ứng dụng',
    faq_how_to_quiz: 'Cách làm bài thử thách',
    faq_how_to_learn: 'Cách đăng ký và đăng nhập',
    faq_use_content: 'Chào mừng bạn đến với KhmerGo! Để sử dụng ứng dụng, bạn có thể bắt đầu bằng cách khám phá các ngôi chùa tại mục Trang chủ, tham gia trả lời câu đố tại mục Thử thách để tích lũy điểm và thăng hạng.',
    faq_quiz_content: 'Mỗi bài thử thách sẽ có các câu hỏi về văn hóa và ngôn ngữ Khmer. Bạn cần chọn câu trả lời đúng trong thời gian quy định để nhận được điểm thưởng.',
    faq_learn_content: 'Bạn có thể đăng ký tài khoản mới bằng email tại màn hình Đăng ký. Sau khi có tài khoản, hãy sử dụng thông tin đó để Đăng nhập và trải nghiệm đầy đủ các tính năng của ứng dụng như tích lũy điểm và thăng hạng.',

    // Home Screen
    promotions: 'Khám phá ngay',
    category: 'Danh mục',
    see_all: 'Xem tất cả...',
    get_coupon: 'Xem',
    learn_now: 'Học ngay',
    temple: 'Ngôi chùa Khmer',
    culture: 'Văn hóa Khmer',
    food: 'Ẩm thực Khmer',
    language_study: 'Học tiếng Khmer',
    ai_camera: 'AI Camera Khmer',
    som_rong_temple: 'Chùa Som Rong',
    oc_om_boc_festival: 'Lễ hội Oóc Om Bóc',
    tra_vinh_vn: 'Trà Vinh, VN',
    soc_trang_vn: 'Sóc Trăng, VN',
    promo_pagoda_title: 'Khám phá vẻ đẹp của các ngôi chùa Khmer',
    tagline: 'Khám phá nền văn hóa Khmer',
    search_placeholder: 'Tìm kiếm địa điểm...',
    location: 'Vị trí',
    search: 'Tìm kiếm',
    discovery_time: 'Thời gian khám phá',
    current_discovery: 'Khám phá gần đây',
    new_discovery: 'Khám phá mới',
    you: 'Bạn',

    // Auth Screens
    login_title: 'Đăng nhập',
    register_title: 'Đăng ký',
    register_account: 'Đăng ký tài khoản',
    email_label: 'Email',
    password_label: 'Mật khẩu',
    confirm_password_label: 'Xác nhận mật khẩu',
    fullname_placeholder: 'Họ và tên',
    processing: 'Đang xử lý...',
    registering: 'Đang tạo tài khoản...',
    login_with: 'Đăng nhập bằng',
    terms: 'Điều khoản dịch vụ',
    error_required: 'Điền đầy đủ thông tin',
    email_in_use: 'Email đã tồn tại hoặc đã được sử dụng bởi tài khoản khác',
    fullname_label: 'Họ và tên',
    select_interests_title: 'Bạn quan tâm đến gì nào',

    // New Home & Pagoda Strings
    welcome_hello: 'Chào mừng 👋',
    explore_categories: 'Danh mục khám phá',
    suggestions_for_you: 'Gợi ý cho bạn',
    oc_om_boc_time: 'Lễ hội truyền thống của người Khmer Nam Bộ',
    bun_nuoc_leo_desc: 'Gia vị đặc trưng tạo nên hương vị Khmer',
    reviews_label: 'đánh giá',
    no_results: 'Không tìm thấy kết quả',
    nguyet_hoa_vinh_long: 'phường Nguyệt Hóa, tỉnh Trà Vinh',
    loading_preparing: 'Đang chuẩn bị cho hành trình khám phá',
    loading_text: 'Đang tải...',
    register_success: 'Đăng ký tài khoản thành công',
    error_loading_temples: 'Không thể tải dữ liệu chùa Khmer',
    no_temple_data: 'Chưa có dữ liệu chùa Khmer',
    pagoda_detail_title: 'Chi tiết chùa',
    address_not_updated: 'Chưa cập nhật địa chỉ',
    navigate_btn: 'Chỉ đường',
    loading_content: 'Đang tải nội dung...',
    content_updating: 'Đang cập nhật nội dung',
    check_back_later: 'Vui lòng quay lại sau',
    rental_available: 'Cho thuê trang phục',
    description: 'Mô tả',
    no_description: 'Chưa có mô tả cho ngôi chùa này.',
    view_map: 'Xem bản đồ',
    map_location: 'VỊ TRÍ TRÊN BẢN ĐỒ',
    view_directions: 'Xem đường đi',
    daily_knowledge: 'Kiến thức mỗi ngày',
    vocab_translation: 'Dịch văn bản',
    let_learn_khmer: 'Học tiếng Khmer cơ bản',
    let_learn_khmer_desc: 'Tìm hiểu và học một số từ vựng cơ bản',
    learn_by_topic: 'Học theo chủ đề',
    vocab_words: 'từ vựng',
    enter_text: 'Nhập văn bản',
    no_vocab_data: 'Không tìm thấy dữ liệu từ vựng chủ đề này.',
    cat_greetings: 'Chào hỏi thông dụng',
    cat_numbers: 'Số đếm cơ bản',
    cat_family: 'Gia đình thân yêu',
    cat_food: 'Ẩm thực đặc sắc',
    // Toast Messages
    login_success: 'Đăng nhập thành công',
    logout_success: 'Tài khoản đã được đăng xuất',
    notif_on: 'Đã bật nhắc nhở học tập',
    notif_off: 'Đã tắt nhắc nhở học tập',
    chat_on: 'Đã hiện nút trợ lý AI',
    chat_off: 'Đã ẩn nút trợ lý AI',
    lang_changed_vi: 'Đã chuyển sang tiếng Việt',
    lang_changed_km: 'Đã chuyển sang tiếng Khmer',

    // New localization keys
    notifications_title: 'Thông báo',
    no_notifications: 'Chưa có thông báo nào',
    just_now: 'Vừa xong',
    ai_intro: 'Tôi là KhmerGo AI - luôn sẵn sàng khám phá văn hóa, địa điểm và ngôn ngữ Khmer cùng bạn.',
    thinking: 'Đang suy nghĩ...',
    clear_chat_history: 'Đã dọn dẹp lịch sử trò chuyện',
    ai_error_connection: 'Xin lỗi, tôi gặp sự cố kết nối. Bạn thử lại nhé!',
    view_details: 'Xem chi tiết',
    explore_now: 'Khám phá ngay',
    ask_anything_placeholder: 'Hỏi bất cứ điều gì...',
    welcome_back: 'Chào mừng bạn quay lại',
    forgot_password: 'Quên mật khẩu',
    use_other_account: 'Sử dụng tài khoản khác',
    account_blocked: 'Tài khoản của bạn đã bị khóa',
    ai_camera_ready: 'Sẵn sàng phân tích',
    ai_camera_idle_title: 'Chào bạn nhé',
    ai_camera_idle_desc: 'Tải ảnh lên hoặc chụp ảnh liên quan đến văn hóa Khmer Nam Bộ. KhmerGo AI sẽ hỗ trợ phân tích và giải thích chi tiết.',
    ai_camera_selected_desc: 'Đã chọn ảnh. Nhấn “Bắt đầu phân tích” để KhmerGo AI khám phá và giải thích ý nghĩa văn hóa của hiện vật này.',
    ai_analyzing: 'Đang phân tích hình ảnh...',
    ai_start_analysis: 'BẮT ĐẦU PHÂN TÍCH',
    ai_result_title: 'Phân tích từ AI',
    ai_unknown_object: 'Vật thể không xác định',
    ai_unknown_desc: 'Hiện vật này hiện chưa khớp với dữ liệu nhận diện trong hệ thống KhmerGo AI. Vui lòng thử lại với hình ảnh rõ nét hơn hoặc góc chụp khác để AI có thể phân tích chính xác hơn.',
    connection_error_title: 'Lỗi kết nối',
    connection_error_desc: 'Vui lòng thử lại sau giây lát.',
    clear_analysis_success: 'Đã dọn dẹp kết quả phân tích',
    features_label: 'Đặc điểm nhận diện',
    translation_error: 'Đã có lỗi xảy ra. Hãy kiểm tra kết nối mạng.',
    avatar_label: 'Ảnh đại diện',
    terms_modal_title: 'ĐIỀU KHOẢN DỊCH VỤ',
    terms_modal_understand: 'ĐÃ HIỂU',

    // Tab Labels
    tab_home: 'Trang chủ',
    tab_community: 'Cộng đồng',
    tab_quiz: 'Thử thách',
    tab_profile: 'Hồ sơ',

    // Community
    comments_title: 'Bình luận',
    create_post_title: 'Tạo bài viết',
    edit_post_title: 'Sửa bài viết',
    post_placeholder: 'Chia sẻ khoảnh khắc đẹp...',
    submit_post: 'Đăng bài',
    update_post: 'Cập nhật',
    empty_posts: 'Chưa có bài viết nào',
    image_label: 'Ảnh',
    update_post_success: 'Đã cập nhật bài viết thành công',
    post_success: 'Đã đăng bài viết thành công',
    action_failed: 'Thao tác thất bại',
    someone_liked: 'đã thích bài viết của bạn',
    someone_replied: 'đã trả lời bình luận của bạn',
    someone_commented: 'đã bình luận bài viết của bạn',
    delete_comment_success: 'Đã xóa bình luận',
    delete_post_success: 'Đã xóa bài viết thành công',
    photo_permission_error: 'Vui lòng cấp quyền truy cập ảnh trong cài đặt',
    image_too_heavy: 'Ảnh quá nặng, hãy chọn ảnh khác',
    image_process_error: 'Lỗi xử lý hình ảnh',
    user_default: 'Người dùng',
    reply_action: 'Trả lời',
    delete_action: 'Xóa',
    first_comment_msg: 'Hãy là người đầu tiên bình luận',
    replying_to: 'Đang trả lời',
    write_comment_placeholder: 'Viết bình luận...',
    edit_post_menu: 'Chỉnh sửa bài viết',
    delete_post_menu: 'Xóa bỏ bài viết',
    delete_post_confirm: 'Xóa bài viết',
    cannot_undo: 'Hành động này không thể hoàn tác',
  },
  km: {
    // Common
    leaderboard: 'តារាងពិន្ទុ',
    weekly: 'ប្រចាំសប្តាហ៍',
    all_time: 'គ្រប់ពេល',
    settings: 'ការកំណត់កម្មវិធី',
    language: 'ភាសា',
    vietnamese: 'ភាសាវៀតណាម',
    khmer: 'ភាសាខ្មែរ',
    back: 'ត្រឡប់ក្រោយ',
    confirm: 'បញ្ជាក់',
    close: 'បិទ',
    save: 'រក្សាទុក',
    cancel: 'បោះបង់',
    continue: 'បន្ត',
    exit: 'ចាកចេញ',
    login: 'ចូល',
    login_user: 'ចូល',
    // Settings Screen
    notif_settings: 'ការជូនដំណឹង',
    study_reminder: 'រំលឹកការសិក្សារាល់ថ្ងៃ',
    reminder_time: 'ម៉ោងរំលឹក',
    app_info: 'ព័ត៌មានកម្មវិធី',
    intro: 'អំពីយើង',
    version: 'ជំនាន់',
    assistant_settings: 'ជំនួយការ AI',
    show_chat_button: 'បង្ហាញប៊ូតុងជជែក AI',
    // Support Screen
    support_feedback: 'ជំនួយ និងមតិកែលម្អ',
    feedback_type: 'ប្រភេទមតិកែលម្អ',
    suggestion: 'មតិកែលម្អ',
    report_issue: 'រាយការណ៍បញ្ហា',
    subject: 'ប្រធានបទ',
    detail: 'ខ្លឹមសារលម្អិត',
    send_feedback: 'ផ្ញើមតិកែលម្អ',
    login_to_send: 'ចូលដើម្បីផ្ញើមតិ',
    // Profile Screen
    my_profile: 'ប្រវត្តិរូបរបស់ខ្ញុំ',
    edit_profile: 'កែសម្រួលប្រវត្តិរូប',
    favorites: 'មាតិកាដែលចូលចិត្ត',
    achievements: 'សមិទ្ធផលរបស់ខ្ញុំ',
    logout: 'ចាកចេញ',
    logout_full: 'ចាកចេញពីគណនី',
    points: 'ពិន្ទុ',
    rank: 'ចំណាត់ថ្នាក់',
    guest: 'ភ្ញៀវ',
    login_to_view: 'ចូលដើម្បីមើលព័ត៌មាន',
    login_to_use: 'ចូលដើម្បីប្រើប្រាស់មុខងារនេះ',
    logout_confirm_msg: 'តើអ្នកប្រាកដថាចង់ចាកចេញមែនទេ?',
    login_required: 'តម្រូវឱ្យចូល',

    // Quiz Screen
    quiz_title: 'ការសាកល្បង',
    question: 'សំណួរ',
    start_quiz: 'ចាប់ផ្តើម',
    daily_challenge: 'ការសាកល្បងប្រចាំថ្ងៃ',
    correct: 'ត្រឹមត្រូវ',
    wrong_answer: 'ខុសហើយ',
    quiz_desc: 'ឆ្លងកាត់សំណួរដើម្បីទទួលបានពិន្ទុបន្ថែម!',
    total_score: 'ពិន្ទុរួម',
    current_rank: 'ចំណាត់ថ្នាក់បច្ចុប្បន្ន',
    categories: 'ប្រធានបទ',
    history: 'ប្រវត្តិសាស្ត្រ',
    geography: 'ភូមិសាស្ត្រ',
    questions: 'សំណួរ',
    performance: 'សមិទ្ធផល',
    view_all: 'មើលទាំងអស់',
    completed: 'បានបញ្ចប់',
    accuracy: 'ភាពត្រឹមត្រូវ',
    recent_performance: 'ផ្អែកលើការសាកល្បងថ្មីៗ',
    choose_topic: 'តើអ្នកចង់រៀនអ្វីនៅថ្ងៃនេះ',
    general_knowledge: 'ចំណេះដឹងទូទៅ',
    pagoda_quiz: 'វត្តអារាមខ្មែរ',
    culture_quiz: 'វប្បធម៌ខ្មែរ',
    food_quiz: 'ម្ហូបខ្មែរ',
    vocab_quiz: 'រៀនភាសាខ្មែរ',
    vocab_quiz_subtitle: 'ផ្គូផ្គងពាក្យខ្មែរ - វៀតណាម',
    vocab_challenge_questions: 'សំណួរសាកល្បងវាក្យសព្ទ',
    correct_answer_points_msg: '+5 ពិន្ទុសម្រាប់ចម្លើយត្រឹមត្រូវ',
    login_required_long_msg: 'អ្នកត្រូវចូលដើម្បីចូលរួមការសាកល្បង និងសន្សំពិន្ទុចំណាត់ថ្នាក់',
    exit_game_title: 'ចាកចេញពីហ្គេម',
    exit_game_msg: 'វឌ្ឍនភាពរបស់អ្នកនឹង\nមិនត្រូវបានរក្សាទុកទេ',
    replay: 'លេងម្តងទៀត',
    choose_another_quiz: 'ជ្រើសរើសការសាកល្បងផ្សេងទៀត',
    answered_correctly: 'ឆ្លើយបានត្រឹមត្រូវ',
    questions_count: 'សំណួរ',
    points_earned: 'ពិន្ទុដែលប្រមូលបាន',
    saving_results: 'កំពុងរក្សាទុកសមិទ្ធផល...',
    results_saved: 'រក្សាទុកសមិទ្ធផលបានជោគជ័យ',
    excellent: '🎉 ពូកែណាស់',
    well_done: '👏 ល្អណាស់',
    keep_it_up: '💪 ខិតខំឡើង',

    // Matching Game
    matching_challenge: 'ផ្គូផ្គងពាក្យ',
    matching_challenge_title: 'ការសាកល្បងផ្គូផ្គង',
    matching_challenge_desc: 'សូមផ្គូផ្គងពាក្យខ្មែរ និងអត្ថន័យភាសាវៀតណាមឱ្យបានលឿន!',
    start_matching: 'ចាប់ផ្តើមផ្គូផ្គង',


    // Personal Info
    personal_info: 'ព័ត៌មានផ្ទាល់ខ្លួន',
    full_name: 'ឈ្មោះពេញ',
    email: 'អ៊ីមែល',
    change_password: 'ផ្លាស់ប្តូរពាក្យសម្ងាត់',
    current_password: 'ពាក្យសម្ងាត់បច្ចុប្បន្ន',
    new_password: 'ពាក្យសម្ងាត់ថ្មី',
    confirm_new_password: 'បញ្ជាក់ពាក្យសម្ងាត់ថ្មី',
    save_changes: 'រក្សាទុកការផ្លាស់ប្តូរ',
    error: 'កំហុស',
    name_required: 'ឈ្មោះមិនអាចនៅទំនេរទេ',
    unsaved_changes: 'ការផ្លាស់ប្តូរដែលមិនបានរក្សាទុក',
    exit_confirm_msg: 'តើអ្នកប្រាកដថាចង់ចាកចេញមែនទេ? ការផ្លាស់ប្តូរបស់អ្នកនឹងត្រូវបាត់បង់។',
    stay: 'នៅបន្ត',
    not_logged_in: 'មិនទាន់បានចូល',
    pass_fields_required: 'សូមបំពេញគ្រប់ព័ត៌មានដើម្បីប្តូរពាក្យសម្ងាត់',
    pass_mismatch: 'ពាក្យសម្ងាត់ថ្មីមិនត្រូវគ្នា',
    pass_too_short: 'ពាក្យសម្ងាត់ថ្មីយ៉ាងហោចណាស់ ៦ តួអក្សរ',
    user_not_found: 'រកមិនឃើញគណនី',
    wrong_old_pass: 'ពាក្យសម្ងាត់បច្ចុប្បន្នមិនត្រឹមត្រូវ',
    update_success: 'បច្ចុប្បន្នភាពបានជោគជ័យ',
    update_failed: 'បច្ចុប្បន្នភាពបរាជ័យ',
    // Support Screen Extra
    faq: 'សំណួរដែលសួរញឹកញាប់',
    feedback_section: 'ផ្ញើមតិកែលម្អមកយើង',
    feedback_placeholder: 'បញ្ចូលខ្លឹមសារមតិកែលម្អ...',
    subject_placeholder: 'បញ្ចូលប្រធានបទមតិ...',
    subject_required: 'សូមបញ្ចូលប្រធានបទ',
    content_required: 'សូមបញ្ចូលខ្លឹមសារមតិ',
    feedback_success: 'បានផ្ញើមតិដោយជោគជ័យ! អរគុណ។',
    feedback_failed: 'ផ្ញើមតិបរាជ័យ។ សូមព្យាយាមម្តងទៀត។',
    tap_to_see_guide: 'ចុចដើម្បីមើលការណែនាំលម្អិត',
    // FAQ Extra
    faq_how_to_use: 'របៀបប្រើកម្មវិធី',
    faq_how_to_quiz: 'របៀបធ្វើតេស្ត',
    faq_how_to_learn: 'របៀបចុះឈ្មោះ និងចូលប្រើប្រាស់',
    faq_use_content: 'សូម chào មកកាន់ KhmerGo! ដើម្បីប្រើកម្មវិធី អ្នក có thể ចាប់ផ្តើមដោយការរុករកវត្តអារាមនានានៅក្នុងទំព័រដើម ចូលរួមឆ្លើយសំណួរក្នុងផ្នែកសាកល្បង ដើម្បីបង្កើនពិន្ទុ និងតម្លើងឋានៈ។',
    faq_quiz_content: 'រាល់ការសាកល្បងនីមួយៗនឹងមានសំណួរអំពីវប្បធម៌ និងភាសាខ្មែរbox។ អ្នកត្រូវជ្រើសរើសចម្លើយដែលត្រឹមត្រូវក្នុងរយៈពេលកំណត់ ដើម្បីទទួលបានពិន្ទុបន្ថែម។',
    faq_learn_content: 'អ្នកអាចចុះឈ្មោះគណនីថ្មីដោយប្រើអ៊ីមែលនៅក្នុងទំព័រចុះឈ្មោះ។ បន្ទាប់ពីមានគណនីហើយ សូមប្រើព័ត៌មាននោះដើម្បីចូលប្រើប្រាស់ និងទទួលបានបទពិសោធន៍ពេញលេញពីកម្មវិធី ដូចជាការធ្វើតេស្ត និងការសន្សំពិន្ទុ។',

    // Home Screen
    promotions: 'ការផ្សព្វផ្សាយ',
    category: 'ប្រភេទ',
    see_all: 'មើលទាំងអស់...',
    get_coupon: 'ទទួលបានប័ណ្ណ',
    learn_now: 'រៀនឥឡូវនេះ',
    temple: 'វត្តអារាមខ្មែរ',
    culture: 'វប្បធម៌ខ្មែរ',
    food: 'ម្ហូបខ្មែរ',
    language_study: 'រៀនភាសាខ្មែរ',
    ai_camera: 'AI កាមេរ៉ា',
    som_rong_temple: 'វត្តសំពៅរុង',
    oc_om_boc_festival: 'ពិធីបុណ្យអកអំបុក',
    tra_vinh_vn: 'ត្រាវិញ, វៀតណាម',
    soc_trang_vn: 'សុកត្រាំង, វៀតណាម',
    promo_pagoda_title: 'ដំណើរស្វែងយល់ពីសម្រស់នៃវត្តអារាមខ្មែរ',
    tagline: 'ស្វែងយល់ពីវប្បធម៌ខ្មែរ',
    search_placeholder: 'ស្វែងរកទីតាំង...',
    location: 'ទីតាំង',
    search: 'ស្វែងរក',
    discovery_time: 'ពេលវេលាស្វែងយល់',
    current_discovery: 'ការស្វែងយល់ថ្មីៗ',
    new_discovery: 'ការស្វែងយល់ថ្មី',
    you: 'អ្នក',

    // Auth Screens
    login_title: 'ចូលគណនី',
    register_title: 'ចុះឈ្មោះ',
    register_account: 'ចុះឈ្មោះគណនី',
    email_label: 'អ៊ីមែល',
    password_label: 'ពាក្យសម្ងាត់',
    confirm_password_label: 'បញ្ជាក់ពាក្យសម្ងាត់',
    fullname_placeholder: 'ឈ្មោះពេញ',
    processing: 'កំពុងដំណើរការ...',
    registering: 'កំពុងបង្កើតគណនី...',
    login_with: 'ចូលតាមរយៈ',
    terms: 'លក្ខខណ្ឌសេវាកម្ម',
    error_required: 'សូមបំពេញព័ត៌មានឱ្យគ្រប់គ្រាន់',
    email_in_use: 'អ៊ីមែលនេះមានរួចហើយ ឬត្រូវបានប្រើប្រាស់ដោយគណនីផ្សេងទៀត',
    fullname_label: 'ឈ្មោះពេញ',
    select_interests_title: 'តើអ្នកចាប់អារម្មណ៍អ្វីខ្លះ?',

    // New Home & Pagoda Strings
    welcome_hello: 'សូមស្វាគមន៍ 👋',
    explore_categories: 'ប្រភេទរុករក',
    suggestions_for_you: 'សំណូមពរសម្រាប់អ្នក',
    oc_om_boc_time: 'ប្រារព្ធឡើងក្នុងខែតុលារៀងរាល់ឆ្នាំ',
    bun_nuoc_leo_desc: 'ម្ហូបពិសេសល្បីឈ្មោះ រសជាតិខ្មែរណាមបូ',
    reviews_label: 'ការវាយតម្លៃ',
    no_results: 'រកមិនឃើញលទ្ធផល',
    nguyet_hoa_vinh_long: 'សង្កាត់ Nguyet Hoa ខេត្ត Tra Vinh',
    loading_preparing: 'កំពុងរៀបចំសម្រាប់ការធ្វើដំណើររុករក',
    loading_text: 'កំពុងទាញយក...',
    register_success: 'ការចុះឈ្មោះបានជោគជ័យ',
    error_loading_temples: 'មិនអាចទាញយកទិន្នន័យវត្តអារាមខ្មែរ',
    no_temple_data: 'មិនមានទិន្នន័យវត្តអារាមខ្មែរ',
    pagoda_detail_title: 'ព័ត៌មានលម្អិត vềវត្ត',
    address_not_updated: 'មិនទាន់មានអាសយដ្ឋាន',
    navigate_btn: 'នាំផ្លូវ',
    loading_content: 'កំពុងទាញយកមាតិកា...',
    content_updating: 'មាតិកាកំពុងត្រូវបានធ្វើបច្ចុប្បន្នភាព',
    check_back_later: 'សូមត្រលប់មកវិញនៅពេលក្រោយ!',
    rental_available: 'ជួលសម្លៀកបំពាក់',
    description: 'ការពិពណ៌នា',
    no_description: 'មិនទាន់មានការពិពណ៌នាសម្រាប់វត្តនេះនៅឡើយទេ។',
    view_map: 'មើលផែនទី',
    map_location: 'ទីតាំងនៅលើផែនទី',
    view_directions: 'មើលផ្លូវធ្វើដំណើរ',
    daily_knowledge: 'ចំណេះដឹងប្រចាំថ្ងៃ',
    vocab_translation: 'បកប្រែវាក្យសព្ទ',
    let_learn_khmer: 'រៀនភាសាខ្មែររាប់បញ្ចូល',
    let_learn_khmer_desc: 'រៀននិងស្វែងយល់ពាក្យមូលដ្ឋានដើម្បីអាចនិយាយប្រាស្រ័យទាក់ទងដោយភាពជឿជាក់នៅពេលជួបបទពិសោធន៍ផ្ទាល់!',
    learn_by_topic: 'រៀនតាមប្រធានបទ',
    vocab_words: 'ពាក្យ',
    enter_text: 'វាយអត្ថបទរបស់អ្នកនៅទីនេះ',
    no_vocab_data: 'រកមិនឃើញទិន្នន័យវាក្យសព្ទសម្រាប់ប្រធានបទនេះទេ។',
    cat_greetings: 'ការសួរសុខទុក្ខបឋម',
    cat_numbers: 'លេខ និងការរាប់',
    cat_family: 'គ្រួសារ និងការហៅទូរសព្ទ',
    cat_food: 'អាហារនិងភេសជ្ជៈ',
    // Toast Messages
    login_success: 'បានចូលដោយជោគជ័យ',
    logout_success: 'បានចាកចេញពីគណនី',
    notif_on: 'បានបើកការរំលឹកការសិក្សា',
    notif_off: 'បានបិទការរំលឹកការសិក្សា',
    chat_on: 'បានបង្ហាញប៊ូតុងជំនួយការ AI',
    chat_off: 'បានលាក់ប៊ូតុងជំនួយការ AI',
    lang_changed_vi: 'បានប្តូរទៅជាភាសាវៀតណាម',
    lang_changed_km: 'បានប្តូរទៅជាភាសាខ្មែរ',

    // Khmer translations for new keys
    notifications_title: 'ការជូនដំណឹង',
    no_notifications: 'មិនទាន់មានការជូនដំណឹងនៅឡើយទេ',
    just_now: 'មុននេះបន្តិច',
    ai_intro: 'ខ្ញុំគឺជា KhmerGo AI - ត្រៀមខ្លួនជានិច្ចដើម្បីរុករកវប្បធម៌ ទីកន្លែង និងភាសាខ្មែរជាមួយអ្នក។',
    thinking: 'កំពុងគិត...',
    clear_chat_history: 'បានសម្អាតប្រវត្តិជជែក',
    ai_error_connection: 'សូមអភ័យទោស ខ្ញុំមានបញ្ហាក្នុងការតភ្ជាប់។ សូមព្យាយាមម្តងទៀត!',
    view_details: 'មើលលម្អិត',
    explore_now: 'រុករកឥឡូវនេះ',
    ask_anything_placeholder: 'សួរអ្វីក៏បាន...',
    welcome_back: 'សូមស្វាគមន៍ការត្រឡប់មកវិញ',
    forgot_password: 'ភ្លេចពាក្យសម្ងាត់',
    use_other_account: 'ប្រើគណនីផ្សេងទៀត',
    account_blocked: 'គណនីរបស់អ្នកត្រូវបានចាក់សោ',
    ai_camera_ready: 'ត្រៀមខ្លួនរួចរាល់សម្រាប់ការវិភាគ',
    ai_camera_idle_title: 'សួស្តីអ្នក',
    ai_camera_idle_desc: 'បង្ហោះរូបភាព ឬថតរូបពាក់ព័ន្ធនឹងវប្បធម៌ខ្មែរណាមបូ។ KhmerGo AI នឹងជួយវិភាគ និងពន្យល់លម្អិត។',
    ai_camera_selected_desc: 'រូបភាពត្រូវបានជ្រើសរើស។ ចុច "ចាប់ផ្តើមការវិភាគ" ដើម្បីឱ្យ KhmerGo AI រុករក និងពន្យល់ពីអត្ថន័យវប្បធម៌នៃវត្ថុនេះ។',
    ai_analyzing: 'កំពុងវិភាគរូបភាព...',
    ai_start_analysis: 'ចាប់ផ្តើមការវិភាគ',
    ai_result_title: 'ការវិភាគពី AI',
    ai_unknown_object: 'វត្ថុមិនស្គាល់អត្តសញ្ញាណ',
    ai_unknown_desc: 'វត្ថុនេះបច្ចុប្បន្នមិនទាន់ត្រូវគ្នានឹងទិន្នន័យសម្គាល់នៅក្នុងប្រព័ន្ធ KhmerGo AI នៅឡើយទេ។ សូមព្យាយាមម្តងទៀតជាមួយរូបភាពច្បាស់ជាងមុន ឬមុំថតផ្សេងទៀត ដើម្បីឱ្យ AI អាចវិភាគបានត្រឹមត្រូវជាងមុន។',
    connection_error_title: 'កំហុសក្នុងការតភ្ជាប់',
    connection_error_desc: 'សូមព្យាយាមម្តងទៀតក្នុងពេលបន្តិចទៀតនេះ។',
    clear_analysis_success: 'បានសម្អាតលទ្ធផលវិភាគ',
    features_label: 'លក្ខណៈសម្គាល់',
    translation_error: 'មានកំហុសបានកើតឡើង។ សូមពិនិត្យមើលការតភ្ជាប់បណ្តាញរបស់អ្នក។',
    avatar_label: 'រូបតំណាង',
    terms_modal_title: 'លក្ខខណ្ឌសេវាកម្ម',
    terms_modal_understand: 'បានយល់',

    // Tab Labels
    tab_home: 'ទំព័រដើម',
    tab_community: 'សហគមន៍',
    tab_quiz: 'ការសាកល្បង',
    tab_profile: 'ប្រវត្តិរូប',

    // Community
    comments_title: 'មតិយោបល់',
    create_post_title: 'បង្កើតអត្ថបទ',
    edit_post_title: 'កែសម្រួលអត្ថបទ',
    post_placeholder: 'ចែករំលែកគ្រាដ៏ស្រស់ស្អាត...',
    submit_post: 'ចុះផ្សាយ',
    update_post: 'ធ្វើបច្ចុប្បន្នភាព',
    empty_posts: 'មិនទាន់មានអត្ថបទនៅឡើយទេ',
    image_label: 'រូបភាព',
    update_post_success: 'បានធ្វើបច្ចុប្បន្នភាពអត្ថបទ',
    post_success: 'បានចុះផ្សាយអត្ថបទ',
    action_failed: 'ប្រតិបត្តិការបរាជ័យ',
    someone_liked: 'បានចូលចិត្តអត្ថបទរបស់អ្នក',
    someone_replied: 'បានឆ្លើយតបមតិរបស់អ្នក',
    someone_commented: 'បានផ្តល់មតិលើអត្ថបទរបស់អ្នក',
    delete_comment_success: 'បានលុបមតិ',
    delete_post_success: 'បានលុបអត្ថបទ',
    photo_permission_error: 'សូមផ្តល់សិទ្ធិចូលប្រើរូបភាពនៅក្នុងការកំណត់',
    image_too_heavy: 'រូបភាពធ្ងន់ពេក សូមជ្រើសរើសរូបភាពផ្សេង',
    image_process_error: 'កំហុសក្នុងការព្យាបាលរូបភាព',
    user_default: 'អ្នកប្រើប្រាស់',
    reply_action: 'ឆ្លើយតប',
    delete_action: 'លុប',
    first_comment_msg: 'សូមក្លាយជាអ្នកដំបូងគេដែលផ្តល់មតិ',
    replying_to: 'កំពុងឆ្លើយតប',
    write_comment_placeholder: 'សរសេរមតិយោបល់...',
    edit_post_menu: 'កែសម្រួលអត្ថបទ',
    delete_post_menu: 'លុបអត្ថបទ',
    delete_post_confirm: 'លុបអត្ថបទ',
    cannot_undo: 'សកម្មភាពនេះមិនអាចផ្លាស់ប្តូរបានទេ',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLangState] = useState<Language>('vi');

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLang = await AsyncStorage.getItem('appLanguage');
      if (savedLang === 'vi' || savedLang === 'km') {
        setLangState(savedLang);
      }
    } catch (error) {
      console.log('Error loading language', error);
    }
  };

  const setLanguage = async (lang: Language) => {
    setLangState(lang);
    try {
      await AsyncStorage.setItem('appLanguage', lang);
    } catch (error) {
      console.log('Error saving language', error);
    }
  };

  const t = (key: string) => {
    const translation = translations[language][key as keyof typeof translations['vi']];
    if (!translation) {
      console.warn(`Missing translation key: ${key} for language: ${language}`);
      return translations['vi'][key as keyof typeof translations['vi']] || key;
    }
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
